// round2/web/animeSolid/src/components/genres/Genres.tsx
import { createResource, Show, For } from "solid-js";
import "./Genres.scss";
import type { genreType } from "tsTypes/Types";
const Fetch = async () => {
  return (
    await fetch(
      "https://gogo-anime-api-sand.vercel.app/api/anime-api/get-genres"
    )
  ).json();
};
function AnimeSlider() {
  const [data] = createResource(Fetch);
  return (
    <>
      <h3>Genres</h3>
      <div class='genres'>
        <Show when={!data.loading} fallback={<div>loading...</div>}>
          <>
            <For each={data().genres}>
              {(item) => (
                <>
                  <Show
                    when={
                      item.genre !== "Hentai" &&
                      item.genre !== "Yaoi" &&
                      item.genre !== "Yuri" &&
                      item.genre !== "Erotica"
                    }>
                    <a href='/'>{item.genre}</a>
                  </Show>
                </>
              )}
            </For>
          </>
        </Show>
        {data() &&
          {
            /* <button onClick={() => console.log(data().genres)}> click</button> */
          }}
      </div>
    </>
  );
}
export default AnimeSlider;

// round2/web/anime/src/comp/page/Genres.tsx
import { useEffect, useState, Dispatch, SetStateAction } from "react";
import { Link } from "react-router-dom";

interface Genresprops {
  setGenre: Dispatch<SetStateAction<string>>;
}

export default function Genres({ setGenre }: Genresprops) {
  const [data, setData] = useState<any[]>([]);
  useEffect(() => {
    FetchData();
  }, []);

  const FetchData = () => {
    fetch(`https://gogo-anime-api-sand.vercel.app/api/anime-api/get-genres`)
      .then((response) => response.json())
      .then((data) => {
        setData(data.genres);
      })
      .catch((err) => {
        console.log("error", err.message);
      });
  };

  return (
    <>
      <div className='genres'>
        {data.map((item: any) => {
          if (
            item.genre !== "Hentai" &&
            item.genre !== "Yaoi" &&
            item.genre !== "Yuri" &&
            item.genre !== "Erotica"
          ) {
            return (
              <Link
                to='/genre'
                key={item.genre}
                onClick={() => {
                  setGenre(item.value);
                }}>
                {item.genre}
              </Link>
            );
          }
        })}
      </div>
    </>
  );
}
