// round2/web/animeSvelte/src/routes/+page.svelte
<script lang="ts">
  //import { onMount } from "svelte";
  //import RecentEpisodes from "./RecentEpisodes.svelte";
  import { writable } from "svelte/store";
  import AnimeSlider from "./AnimeSlider.svelte";

  /* const view = writable({
    subOrDub: 1,
  }); */

  let subOrDub: number = 1;

  function handleClick() {
    if (subOrDub == 1) {
      subOrDub = 2;
    } else {
      subOrDub = 1;
    }
  }
</script>

<div>
  <div class="animeWrapper">
    <button on:click={handleClick}>click me</button>
    <AnimeSlider
      endpoint={`https://gogo-anime-api-sand.vercel.app/api/anime-api/recent-release?type=${subOrDub}&page=1`}
      name="Recent release"
    />
  </div>
  <!-- <div class="animeWrapper">
    <AnimeSlider
      endpoint="https://gogo-anime-api-sand.vercel.app/api/anime-api/top-airing"
      name="Top airing"
    />
  </div>
  <div class="animeWrapper">
    <AnimeSlider
      endpoint="https://gogo-anime-api-sand.vercel.app/api/anime-api/popular?page=1"
      name="Popular anime"
    />
  </div>
  <div class="animeWrapper">
    <AnimeSlider
      endpoint="https://gogo-anime-api-sand.vercel.app/api/anime-api/movies?page=1"
      name="movies"
    />
  </div> -->
</div>

<style lang="scss">
  :global(*) {
    margin: 0;
    padding: 0;
  }

  :global(body) {
    background-color: var(--mainBg);
    color: var(--mainTextColor);
  }

  :global(html) {
    width: 100%;
    height: 100%;
  }

  :global(:root) {
    --mainBg: #232946;
    --navBg: #484266;
    --tagsBg: #161929;
    --buttonBg: #fab0db;
    --mainTextColor: white;
  }

  .animeWrapper {
    width: 100%;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr;
    height: 350px;
    text-align: center;
  }
</style>

// round2/web/animeSolid/src/routes/index.tsx
import { Title } from "solid-start";
import { createSignal } from "solid-js";
import AnimeSlider from "~/components/AnimeSlider";
import "./home.scss";

export default function Home() {
  const [subOrDub, setSubOrDub] = createSignal<number>(1);

  return (
    <main>
      <Title>AnimeNexus</Title>
      <div class='animeWrapper'>
        <div class='animeType'>
          <button onclick={() => setSubOrDub(1)}>sub</button>

          <button onclick={() => setSubOrDub(2)}>dub</button>
        </div>
        <AnimeSlider
          endpoint={`https://gogo-anime-api-sand.vercel.app/api/anime-api/recent-release?type=${subOrDub()}&page=1`}
          name='Recent release'
        />
      </div>
      <div class='animeWrapper'>
        <AnimeSlider
          endpoint='https://gogo-anime-api-sand.vercel.app/api/anime-api/top-airing'
          name='Top airing'
        />
      </div>
      <div class='animeWrapper'>
        <AnimeSlider
          endpoint='https://gogo-anime-api-sand.vercel.app/api/anime-api/popular?page=1'
          name='Popular anime'
        />
      </div>
      /*{" "}
      <div class='animeWrapper'>
        <AnimeSlider
          endpoint='https://gogo-anime-api-sand.vercel.app/api/anime-api/movies?page=1'
          name='movies'
        />
      </div>{" "}
      */
    </main>
  );
}
