// round2/web/animeSvelte/src/routes/Genres.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { genreType } from "../../tsTypes/Types";

  /* type test = {
    genres: 
}*/
  let data: genreType[] = [];
  let error: any = "";
  let endpoint: string = `https://gogo-anime-api-sand.vercel.app/api/anime-api/get-genres`;
  onMount(async () => {
    /* fetch(`https://gogo-anime-api-sand.vercel.app/api/anime-api/get-genres`)
      .then((res) => res.json())
      .then((data) => {
        data = data.genres;
      })
      .catch((err) => {
        console.log(err);
      }); */
    try {
      const response = await fetch(endpoint);
      const jsonData = await response.json();
      data = jsonData.genres;
    } catch (err) {
      error = err;
      console.log("error " + err);
    }
  });
</script>

<div class="genres">
  {#each data as item}
    {#if item.genre !== "Hentai" && item.genre !== "Yaoi" && item.genre !== "Yuri" && item.genre !== "Erotica"}
      <a href="/">{item.genre}</a>
    {/if}
  {:else}
    <div class="loadingWrapper">
      <h1 class="loading">loading...</h1>
    </div>
  {/each}
</div>

<style lang="scss">
  .genres {
    margin: 0 auto;
    padding: 10px;
    width: 90%;
    display: flex;
    flex-wrap: wrap;
    gap: 15px;
    background-color: #161929;
    justify-content: center;
    a {
      color: white;
      text-decoration: none;
      padding: 10px;
      background-color: #232946;
      transition: opacity 100ms ease-in-out;
      &:hover {
        opacity: 0.5;
      }
    }
  }
</style>

// round2/web/animeSolid/src/components/genres/Genres.tsx
import { createResource, Show, For } from "solid-js";
import "./Genres.scss";
import type { genreType } from "tsTypes/Types";
const Fetch = async () => {
  return (
    await fetch(
      "https://gogo-anime-api-sand.vercel.app/api/anime-api/get-genres"
    )
  ).json();
};
function AnimeSlider() {
  const [data] = createResource(Fetch);
  return (
    <>
      <h3>Genres</h3>
      <div class='genres'>
        <Show when={!data.loading} fallback={<div>loading...</div>}>
          <>
            <For each={data().genres}>
              {(item) => (
                <>
                  <Show
                    when={
                      item.genre !== "Hentai" &&
                      item.genre !== "Yaoi" &&
                      item.genre !== "Yuri" &&
                      item.genre !== "Erotica"
                    }>
                    <a href='/'>{item.genre}</a>
                  </Show>
                </>
              )}
            </For>
          </>
        </Show>
        {data() &&
          {
            /* <button onClick={() => console.log(data().genres)}> click</button> */
          }}
      </div>
    </>
  );
}
export default AnimeSlider;
