// round2/web/tryingVue/src/App.vue
<template>
  <form @submit.prevent="addTodo">
    <input type="text" v-model="userInput" />
    <button>add todo</button>
  </form>
  <ul class="todoWrapper">
    <li v-for="todo in todoArray">
      <p :class="todo.isDone ? 'done' : ''" @click="ToggleTodoIsDone(todo.id)">
        {{ todo.title }}
      </p>
      <button @click="deleteTodo(todo.id)">X</button>
    </li>
  </ul>
</template>

<script lang="ts">
let id = 1;
interface todoTypes {
  id: number;
  title: string;
  isDone: boolean;
}

type Data = {
  todoArray: todoTypes[];
  userInput: string;
};

export default {
  data(): Data {
    return {
      todoArray: [],
      userInput: "",
    };
  },
  methods: {
    addTodo() {
      if (this.userInput != "") {
        this.todoArray.push({ id: id, title: this.userInput, isDone: false });
        id++;
      }
    },
    deleteTodo(id: number) {
      const temp: todoTypes[] = [...this.todoArray];
      const index = this.todoArray.findIndex((item) => item.id == id);
      temp.splice(index, 1);
      this.todoArray = temp;
    },
    ToggleTodoIsDone(id: number) {
      const temp = [...this.todoArray];
      const index = this.todoArray.findIndex((item) => item.id === id);
      temp[index].isDone = !temp[index].isDone;
      this.todoArray = temp;
    },
  },
  /* methods: {
    changeNumber(number: number) {
      this.count = number;
    },
  }, */
  /* computed: {
    counted() {
      const counted = this.count;
      return counted;
    },
  }, */
};
</script>

// round2/web/todo/src/App.tsx
import React, { useEffect, useState } from "react";

import "./App.scss";

interface todosType {
  id: number;
  title: string;
  isDone: boolean;
}

function App() {
  const [userInput, setUserInput] = useState<string>("");
  const [todos, setTodos] = useState<Array<todosType>>([]);
  const HandleSubmit = (e: any) => {
    e.preventDefault();
    const d = new Date();
    if (userInput !== "") {
      let temp: todosType = {
        id: d.getTime(),
        title: userInput,
        isDone: false,
      };
      setTodos([...todos, temp]);
      setUserInput("");
    }
  };
  const Delete = (id: number) => {
    const temp = [...todos];
    const index = todos.findIndex((item) => item.id === id);
    temp.splice(index, 1);
    setTodos(temp);
  };
  const ToggleIsDone = (id: number) => {
    const temp = [...todos];
    const index = todos.findIndex((item) => item.id === id);
    temp[index].isDone = !temp[index].isDone;
    setTodos(temp);
  };
  return (
    <>
      <div className='App'>
        <form onSubmit={HandleSubmit}>
          <input
            maxLength={20}
            type='text'
            onChange={(e) => {
              setUserInput(e.target.value);
            }}
          />
        </form>
        <div className='todosWrapper'>
          {todos.map((item: todosType) => {
            return (
              <div key={item.id}>
                <p
                  onClick={() => {
                    ToggleIsDone(item.id);
                  }}
                  className={item.isDone ? "done" : ""}>
                  {item.title}
                </p>
                <button
                  onClick={() => {
                    Delete(item.id);
                  }}>
                  x
                </button>
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
}

export default App;
